project:
  type: website

website:
  title: "Bisma Rohpanca Joyosumarto (BismaBRJ)"
  navbar:
    left:
      - data_software.qmd
      - teaching_tutoring.qmd
    right:
      - icon: github
        href: https://www.github.com/BismaBRJ
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/bisma-rohpanca-joyosumarto
        aria-label: LinkedIn

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



